title: Math4AI
description: Math4AI site (MSc AI, UvA).
theme: just-the-docs

url: https://FloorEijkelboom.github.io/math4ai

search_enabled: true

mermaid:
  version: "9.1.3"

callouts:
  summary:
    title: Summary
    color: green
  content:
    title: Content (tl;dr)
    color: green
  exercise:
    title: Exercise
    color: blue
  example:
    title: Example
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red